apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  namespace: remi-namespace
  labels:
    name: hello-world
spec:
  containers:
  - name: hello-world
    image: dockercloud/hello-world
    ports:
      - containerPort: 80
